### ISSUE TITLE
ninja error when rm_work

### ISSUE THREAD

**Issue by rbroucquart** [ChimeraTK/meta-chimeratk#9] opened 2024-02-20 16:47 UTC
When rm_work is inherited in the project, building applicationCore or controlsystemadapter-opc-ua-adapter fails

I encounter error such as 
`ninja: build stopped: subcommand failed`

When running again, I go further and succeed to build applicationcore, but fails again on

```
ERROR: controlsystemadapter-opc-ua-adapter-03.02.02-r0 do_compile: Execution of '/tmp/yoctodir/work/aarch64-xilinx-linux/controlsystemadapter-opc-ua-adapter/03.02.02-r0/temp/run.do_compile.27581' failed with exit code 1:
ninja: error: '/tmp/yoctodir/work/aarch64-xilinx-linux/controlsystemadapter/02.08.00-r0/recipe-sysroot/usr/lib/libatomic.so', needed by 'libChimeraTK-ControlSystemAdapter-OPCUAAdapter.so.03.02.02', missing and no known rule to make it

ERROR: Task (/home/sources/diagnostics/broucquart/fofb-yocto/build_damc_fofb/../sources/meta-chimeratk/recipes-applicationcore/controlsystemadapter-opc-ua-adapter/controlsystemadapter-opc-ua-adapter_03.02.02.bb:do_compile) failed with exit code '1'
ERROR: applicationcore-03.04.00-r0 do_compile: Execution of '/tmp/yoctodir/work/aarch64-xilinx-linux/applicationcore/03.04.00-r0/temp/run.do_compile.27584' failed with exit code 1:
ninja: error: '/tmp/yoctodir/work/aarch64-xilinx-linux/controlsystemadapter/02.08.00-r0/recipe-sysroot/usr/lib/libatomic.so', needed by 'libChimeraTK-ApplicationCore.so.03.04.00', missing and no known rule to make it
```

To get around, I can add the recipes to the RM_WORK_EXCLUDE

**Comment by phako** [comment] 2024-02-21 09:14
Hm. Thought I had found all of those issues with paths creeping in - which commit are you on?

**Comment by rbroucquart** [comment] 2024-02-21 09:28
Sorry I should have mentioned.
I'm on branch zeus (065b58ca)

I'll probably upgrade soon the project to kirkstone anyway

**Comment by phako** [comment] 2024-02-21 09:29
That is basically latest greatest, there seems to be still something lurking around, but rm_work seems to be the way to find them finnally

**Comment by phako** [comment] 2024-02-21 09:41
Might be that the OPC-UA adapter is not ported to CMake targets yet (at least in the version that is in yocto) :thinking:

**Comment by phako** [comment] 2024-03-18 15:07
It's caused by the constrolsystemadapter's way of linking to libatomic. Simple fix, will push soonish

**Comment by phako** [comment] 2024-03-19 08:12
Should be fixed now

**Closed as completed by phako** 2024-03-19 08:12 UTC
